name: Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-node-server .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_USERNAME }} | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin"

      - name: Push Docker image to Docker Hub
        run: docker push my-node-server

      - name: Deploy to server
        run: |
          ssh user@server-ip-address "docker pull my-node-server"
          ssh user@server-ip-address "docker run -d -p 3000:3000 --name my-node-container my-node-server"